---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[chef_metal::default]
    attributes:

suites:
  - name: openstack
    run_list:
    - recipe[chef_metal_test::openstack]
    attributes:
      chef_metal:
        openstack_username: <%= ENV['OS_USERNAME'] %>
        openstack_api_key: <%= ENV['OS_PASSWORD'] %>
        openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>
        openstack_tenant: <%= ENV['OS_TENANT'] %>
